### ISSUE TITLE
It says invalid preamble on every file I feed

### ISSUE THREAD

**Issue by Imtiaz08** [unalfaruk/SoftGNSS#1]
Hi I am facing an issue when using the softGNSS. I have tired using different .bin files but it says invalid preamble on all of them. 

currently I am using settings 

IF = 0 Hz
sampling freq = 2.5 MHz/ 4.0 MHz 
number of ms to process = 37000
dt acq threshold = 1.5 (it never detects signal at 2.5)

**Comment by unalfaruk** [comment]
Hey @Imtiaz08,

Please try the link below for demo signals which I tried for verification:
[Google Drive, IF GNSS Signals](https://drive.google.com/drive/folders/1oPOW9idULvt-I1ZICS3jVAkXVNW0q3eU?usp=sharing)

**Comment by Imtiaz08** [comment]
Please tell me about the specifications of the data too. 

what is the IF, sampling frequency etc

**Comment by unalfaruk** [comment]
> Please tell me about the specifications of the data too.
> 
> what is the IF, sampling frequency etc

@Imtiaz08 you can look at the "initSettings.m" files in the repositories. You will find the values.
[TMBOC](https://github.com/TMBOC/SoftGNSS/blob/master/initSettings.m)
[Unalfaruk](https://github.com/unalfaruk/SoftGNSS/blob/master/initSettings.m)

A few files are already located together with a txt file containing specs.

Please try the files and inform us about the issue.
