### ISSUE TITLE
Can you provide some description of the sample data?

### ISSUE THREAD

**Issue by JessSun** [unalfaruk/SoftGNSS#3]
Hi, I was wondering if it would be convenient for you to provide some description of the sample signal, such as the ground truth coordinate and collecting environment, thank you very much.

**Comment by unalfaruk** [comment]
Hi @JessSun,

That's a fair point, however I have no information about it at the moment. I had my results which might be reference for u but could not find it.

You can google it btw, this is not a signal recorded by me, it's a sample signal of the book “A Software-Defined GPS and Galileo Receiver: A Single-Frequency Approach”.
